# Site settings
url: "https://byeongjooahn.github.io"  # Full site URL (no trailing slash)
baseurl: ""                             # User site => keep empty

# Enable official plugin supported by GitHub Pages
plugins:
  - jekyll-sitemap                      # Auto-generates /sitemap.xml at build time